services:
  postgres:
    image: postgres:latest
    container_name: postgres_server
    restart: always
    environment:
      # db username
      POSTGRES_USER: 
      # db password
      POSTGRES_PASSWORD: 
      POSTGRES_DB: Makcii_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql
   
  scraping_script:
    build: ./scraping
    container_name: python_scraper
    environment: 
      - DB_CONNECTION_STRING=postgresql+psycopg2://sa:p123@postgres:5432/Makcii_DB
    depends_on:
      - postgres
    volumes:
      - ./scraping:/app
    restart: on-failure
    
volumes:
  postgres_data: