services:
  frontend:
    image: makciiregistry.azurecr.io/frontend
    container_name: frontend
    environment:
      - REACT_APP_SPRING_URL=http://makcii-dnb2cbdphscuf9d8.westeurope-01.azurewebsites.net/spring
    depends_on:
      - spring-backend
    restart: always
   
  scraping-script:
    image: makciiregistry.azurecr.io/scraping-script:latest
    container_name: python-scraper
    environment: 
      - DB_CONNECTION_STRING=postgresql+psycopg2://sa:p123@postgres:5432/Makcii_DB
    depends_on:
      - postgres
    restart: on-failure
  
  fastapi-backend:
    image: makciiregistry.azurecr.io/fastapi-backend:latest
    container_name: fastapi-backend
    environment:
      - DB_CONNECTION_STRING=postgresql+psycopg2://sa:p123@postgres:5432/Makcii_DB
    depends_on:
      - postgres
    restart: always
    
  microservice:
    image: makciiregistry.azurecr.io/microservice:latest
    container_name: microservice
    environment:
      - DB_CONNECTION_STRING=jdbc:postgresql://postgres:5432/Makcii_DB
      - DB_USERNAME=sa
      - DB_PASSWORD=p123
      - PORT=8081
    depends_on:
      - postgres
    restart: always

  spring-backend:
    image: makciiregistry.azurecr.io/spring-backend:latest
    container_name: spring-backend
    environment:
      - DB_CONNECTION_STRING=jdbc:postgresql://postgres:5432/Makcii_DB
      - DB_USERNAME=sa
      - DB_PASSWORD=p123
      - PORT=8080
      - FASTAPI_URL=http://fastapi-backend:8000/predict
      - MICROSERVICE_URL=http://microservice:8081/dayData/microservice
    depends_on:
      - postgres
      - microservice
      - fastapi-backend
    restart: always
      
  postgres:
    image: makciiregistry.azurecr.io/postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: p123
      POSTGRES_DB: Makcii_DB
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sa", "-d", "Makcii_DB"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

  nginx:
    image: makciiregistry.azurecr.io/nginx-reverse-proxy:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - spring-backend
      - fastapi-backend
      - microservice
    restart: always
